Lavacar-main/BDLavacar/BDLavacar/Controllers/FacturaController.cs
using BDLavacar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;


namespace BDLavacar.Controllers
{
    public class FacturaController : Controller
    {
        bdlavacarEntities2 modeloBD = new bdlavacarEntities2();
        #region Ingresar

        #region Registrar
        public ActionResult insertaFactura(int Id_Factura_F)
        {
            sp_RetornaFacturaID_Result modelovista = new sp_RetornaFacturaID_Result();
            modelovista = this.modeloBD.sp_RetornaFacturaID(Id_Factura_F).FirstOrDefault();
            Session["Id_Factura_F"] = Id_Factura_F;
            Session["Nombre"] = modelovista.NombreCompleto;
            Session["cedula"] = modelovista.Cedula_P;
            Session["marca"] = modelovista.Tipo_MV;
            Session["placa"] = modelovista.Placa_V;
            Session["fecha"] = modelovista.Fecha_F;
            Session["total"] = modelovista.Total_F;
            AgregaServicioViewBag();
            return View(modelovista);
        }
        [HttpPost]
        public ActionResult insertaFactura(sp_RetornaFacturaID_Result modeloVista)
        {
            int cantRegistroAfectados = 0;
            string resultado = "";
            try
            {
                cantRegistroAfectados = this.modeloBD.sp_InsertaServicioFactura(
                                        modeloVista.Id_Factura_FVS = Convert.ToInt32(Session["Id_Factura_F"]),
                                        modeloVista.Cantidad_FVS,
                                        modeloVista.Id_Servicio_FVS);
            }
            catch (Exception error)
            {
                resultado = "Ocurrio un error: " + error.Message;
            }
            finally
            {
                if (cantRegistroAfectados > 0)
                {
                    resultado += "Registro Insertado";

                }
                else
                {
                    resultado += "No se pudo insertar";
                }
            }

            Response.Write("<script language=javascript>alert('" + resultado + "');</script>");

            AgregaServicioViewBag();
            return View();
        }
        #endregion

        #region Prefactura

        public ActionResult RegistraFactura()
        {
            return View();
        }
        [HttpPost]
        public ActionResult RegistraFactura(sp_RetornaFacturas_Result modeloVista)
        {
            int cantRegistroAfectados = 0;
            string resultado = "";
            try
            {
                cantRegistroAfectados = this.modeloBD.sp_RegistraFacturas(
                                        modeloVista.Id_Vehiculo_F,
                                        modeloVista.Id_Persona_F

                                        );
            }
            catch (Exception error)
            {
                resultado = "Ocurrio un error: " + error.Message;
            }
            finally
            {
                if (cantRegistroAfectados > 0)
                {
                    resultado += "Registro Insertado";

                }
                else
                {
                    resultado += "No se pudo insertar";
                }
            }

            Response.Write("<script language=javascript>alert('" + resultado + "');</script>");
            Response.Redirect("~/Factura/ListaPreFactura");


            return View();
        }
        #endregion

        #endregion


        #region Mostrar
        public ActionResult ListaPreFactura()
        {
            List<sp_RetornaFacturaNULL_Result> modeloVista =
            new List<sp_RetornaFacturaNULL_Result>();

            modeloVista = modeloBD.sp_RetornaFacturaNULL().ToList();
            return View(modeloVista);
        }

        public ActionResult KendoFactura()
        {
            return View();
        }

        [HttpPost]
        public ActionResult KendoFacturaLista()
        {
            List<sp_RetornaFacturaFinal_Result> listaPersonas =
               this.modeloBD.sp_RetornaFacturaFinal().ToList();
            return Json(new
            {
                resultado = listaPersonas
            });
        }


        public ActionResult MuestraServicios(int Id_Factura_F)
        {
            Session["Id_Facturas_F"] = Id_Factura_F;
            sp_RetornaFacturaServicio_Result modelovista = new sp_RetornaFacturaServicio_Result();
            modelovista = this.modeloBD.sp_RetornaFacturaServicio(Id_Factura_F).FirstOrDefault();
            
            return View(modelovista);
        }
        [HttpPost]
        public ActionResult MuestraServiciosLista(sp_RetornaFacturaServicio_Result modelovista)
        {
            List<sp_RetornaFacturaServicio_Result> listaPersonas =
               this.modeloBD.sp_RetornaFacturaServicio(modelovista.Id_Factura_F = Convert.ToInt32(Session["Id_Facturas_F"])).ToList();

            return Json(new
            {
                resultado = listaPersonas
            });
        }

        #endregion

        #region Void
        void AgregaServicioViewBag()
        {
            this.ViewBag.Servicio = this.modeloBD.sp_RetornaServicios().ToList();
        }
        #endregion

        #region Json
        public ActionResult RetornaPersona()
        {
            List<sp_RetornaClientesPreFactura_Result> Persona = this.modeloBD.sp_RetornaClientesPreFactura().ToList();
            return Json(Persona);
        }

        public ActionResult RetornaVehiculo()
        {
            List<sp_RetornaVehiculoUI_Result> Carro = this.modeloBD.sp_RetornaVehiculoUI().ToList();
            return Json(Carro);
        }
        #endregion

        #region Eliminar
        #region Eliminar Prefactura
        public ActionResult PreFacturaEliminar(int Id_Factura_F)
        {
            sp_RetornaPreFacturaID_Result modelovista = new sp_RetornaPreFacturaID_Result();
            modelovista = this.modeloBD.sp_RetornaPreFacturaID(Id_Factura_F).FirstOrDefault();
            return View(modelovista);
        }

        [HttpPost]
        public ActionResult PreFacturaEliminar(sp_RetornaPreFacturaID_Result modelovista)
        {
            int cantRegistrosAfectados = 0;
            string resultado = "";
            try
            {
                cantRegistrosAfectados = this.modeloBD.sp_EliminarPreFactura(
                    modelovista.Id_Factura_F);
            }
            catch (Exception error)
            {
                resultado = "Ocurrio un error: " + error.Message;
            }
            finally
            {
                if (cantRegistrosAfectados > 0)
                {
                    resultado += "Registro Eliminado";
                }
                else
                {
                    resultado += "No se pudo Eliminado";
                }

            }
            Response.Write("<script language=javascript>alert('" + resultado + "')</script>");
           
            return View(modelovista);


        }
        # endregion

        public ActionResult EliminaServicioFactura(int Id_Servicio_S)
        {
            Session["Id_Servicio_S"]= Id_Servicio_S;
            sp_RetornaFacturaServicioID_Result modeloVista = new sp_RetornaFacturaServicioID_Result();
            modeloVista = this.modeloBD.sp_RetornaFacturaServicioID(Convert.ToInt32(Session["Id_Facturas_F"]), Id_Servicio_S).FirstOrDefault();
            return View(modeloVista);
        }

        [HttpPost]
        public ActionResult EliminaServicioFactura(sp_RetornaFacturaServicioID_Result modelovista)
        {
            int cantRegistrosAfectados = 0;
            string resultado = "";
            int Id_Facturas_F = Convert.ToInt32(Session["Id_Facturas_F"]);
            int Id_Servicio_S = Convert.ToInt32(Session["Id_Servicio_S"]);
            try
            {
                cantRegistrosAfectados = this.modeloBD.sp_EliminaServicioFactura(
                    Id_Facturas_F, Id_Servicio_S);
            }
            catch (Exception error)
            {
                resultado = "Ocurrio un error: " + error.Message;
            }
            finally
            {
                if (cantRegistrosAfectados > 0)
                {
                    resultado += "Servicio eliminado de la lista";
                }
                else
                {
                    resultado += "No se pudo eliminar el servicio";
                }

            }
            Response.Write("<script language=javascript>alert('" + resultado + "')</script>");

            Response.Redirect("~/Factura/MuestraServicios?Id_Factura_F=" + Id_Facturas_F);
            return View(modelovista);


        }

        #endregion


        #region Modificar

        public ActionResult ModificaServicioFactura(int Id_Servicio_S)
        {
            
            sp_RetornaFacturaServicioID_Result modeloVista = new sp_RetornaFacturaServicioID_Result();
            modeloVista = this.modeloBD.sp_RetornaFacturaServicioID(Convert.ToInt32(Session["Id_Facturas_F"]), Id_Servicio_S).FirstOrDefault();
            Session["Cantidad"] = modeloVista.Cantidad_FVS;
            Session["Servicio"] = modeloVista.Tipo_S;
            Session["Estado"] = modeloVista.Estado_FVS;
            Session["Fecha"] = modeloVista.Fecha_F;
            return View(modeloVista);
        }


        [HttpPost]
        public ActionResult ModificaServicioFactura(sp_RetornaFacturaServicioID_Result modeloVista)
        {
            int cantRegistroAfectados = 0;
            string resultado = "";
            int Id_Facturas_F = Convert.ToInt32(Session["Id_Facturas_F"]);
            try
            {
                cantRegistroAfectados = this.modeloBD.sp_ModificaServicioFactura(
                                        Id_Facturas_F,
                                        modeloVista.Cantidad_FVS,
                                        modeloVista.Id_Servicio_S,

Lavacar-main/BDLavacar/BDLavacar/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BDLavacar.Models;

namespace BDLavacar.Controllers
{
    public class LoginController : Controller
    {

        bdlavacarEntities2 modeloBD = new bdlavacarEntities2();

  
        public ActionResult InicioSesion()
        {
            return View();
        }
        public ActionResult Validar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Validar(string correo, string contra)
        {
            Session["correoVista"] = correo;
            string url = "";
            string mensaje = "";

            try
            {
                sp_RetornaLogueo_Result datosCliente = new sp_RetornaLogueo_Result();
                datosCliente = modeloBD.sp_RetornaLogueo(correo, contra).FirstOrDefault();

                if (datosCliente == null)
                {
                    Response.Write("<script>alert('Datos Invalidos')</script>"); ;
                    this.Session.Add("Nombre", null);
                    this.Session.Add("Tipo", null);
                    this.Session.Add("Fecha", null);
                    this.Session.Add("UsuarioLogeado", false);

                }
                else
                {

                    Session.Add("Nombre" , datosCliente.@Nombre);
                    Session.Add("Tipo",datosCliente.@Tipo);
                    Session.Add("Fecha",datosCliente.@Fecha);
                    Session.Add("UsuarioLogeado",true);

                    if (Convert.ToInt32(this.Session["Tipo"]) == 1)
                    {
                        url = Url.Action("Inicio", "Home");
                      
                    }
                    else if (Convert.ToInt32(this.Session["Tipo"]) == 2)
                    {
                        url = Url.Action("ClientesVistaLista", "ClienteVista");
                     
                    }
                   
                    mensaje = "Usted ha ingresado: " + Session["Nombre"];
                }
            }
            catch (Exception excepcionCapturada)
            {
                mensaje += $"Ocurrio un error:{excepcionCapturada.Message}";
            }

            return Json(new { resultado = mensaje,validado=Session["UsuarioLogeado"],url= url });


        }
    }
}

Lavacar-main/BDLavacar/BDLavacar/Views/Shared/_LayoutBDLavacar.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <title>@ViewBag.Title</title>
    <link href="https://kendo.cdn.telerik.com/2020.2.617/styles/kendo.common.min.css" rel="stylesheet" />
    <link href="https://kendo.cdn.telerik.com/2020.2.617/styles/kendo.blueopal.min.css" rel="stylesheet" />
    @RenderSection("css", required: false)
    <link href="~/Content/Carrousel.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
   
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LavesuMcqueen", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            Vehículo
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" style="background-color:#e1e1e1">
                            <li>@Html.ActionLink("Consultar Vehículo", "VehiculoLista", "Vehiculo")</li>
                            <li>@Html.ActionLink("Ingresar Vehículo", "VehiculoNuevo", "Vehiculo")</li>
                            <li>@Html.ActionLink("Consultar Marca", "MarcaVehiculoLista", "Vehiculo")</li>
                            <li>@Html.ActionLink("Ingresar Marca", "MarcaVehiculoNuevo", "Vehiculo")</li>
                            <li>@Html.ActionLink("Consultar Tipo", "TipoVehiculoLista", "Vehiculo")</li>
                            <li>@Html.ActionLink("Ingresar Tipo", "TipoVehiculoNuevo", "Vehiculo")</li>
                            <li>@Html.ActionLink("Consultar País", "PaisFabricanteLista", "Vehiculo")</li>
                            <li>@Html.ActionLink("Ingresar País", "PaisFabricanteNuevo", "Vehiculo")</li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            Cliente
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" style="background-color:#e1e1e1">
                            <li>@Html.ActionLink("Consultar Cliente", "ClientesLista", "Clientes")</li>
                            <li>@Html.ActionLink("Ingresar Cliente", "InsertarUsuario", "Clientes")</li>
                            <li>@Html.ActionLink("Agregar Vehículo", "RegistraFactura", "Factura")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            Servicios
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" style="background-color:#e1e1e1">
                            <li>@Html.ActionLink("Consultar Servicios", "ServicioLista", "Servicios")</li>
                            <li>@Html.ActionLink("Ingresar Servicios", "InsertarServicio", "Servicios")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            Factura
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" style="background-color:#e1e1e1">
                            <li>@Html.ActionLink("Crea Factura", "ListaPreFactura", "Factura")</li>
                            <li>@Html.ActionLink("Consultar Factura", "KendoFactura", "Factura")</li>


                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            Reportes
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" style="background-color:#e1e1e1">
                            <li>@Html.ActionLink("Vehículos por cliente", "VehiculosCliente", "Reportes")</li>
                            <li>@Html.ActionLink("Servicios por cliente", "Servicioscliente", "Reportes")</li>
                            <li>@Html.ActionLink("Servicios por vehículo", "ServiciosVehiculo", "Reportes")</li>

                        </ul>
                    </li>
                    <li id="Cerrar">@Html.ActionLink("Cerrar Sesion", "InicioSesion", "Login")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />

    </div>
    <div style=" position: fixed; left: 0; bottom: 0; padding-top:10px;width: 100%; background-color: #000000; color: white; text-align: center">
        <footer class="bg-light text-center text-lg-start">
            <p>&copy; @DateTime.Now.Year - Lavacar</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/myBundle")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/Login/Cerrar_Sesion.js"></script>
</body>
</html>

Lavacar-main/BDLavacar/BDLavacar/Views/Shared/_LayoutCliente.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <title>@ViewBag.Title</title>
    <link href="https://kendo.cdn.telerik.com/2020.2.617/styles/kendo.common.min.css" rel="stylesheet" />
    <link href="https://kendo.cdn.telerik.com/2020.2.617/styles/kendo.blueopal.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("LavesuCar", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Vehiculos", "VehiculoLista", "Vehiculo")</li>
                    <li>@Html.ActionLink("ClienteVista", "ClientesVistaLista", "Inicio")</li>
                    <li>@Html.ActionLink("Servicios", "ServicioLista", "Servicios")</li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown">
                            Reportes
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" style="background-color:#e1e1e1">
                            <li>@Html.ActionLink("Vehículos por cliente", "VehiculosClienteID", "Reportes")</li>
                            <li>@Html.ActionLink("Servicios por cliente", "ServiciosClienteID", "Reportes")</li>
                            <li>@Html.ActionLink("Servicios por vehículo", "ServiciosVehiculoID", "Reportes")</li>

                        </ul>
                    </li>
                    <li>@Html.ActionLink("Cerrar Sesión", "InicioSesion", "Login")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container-fluid body-content">
        @RenderBody()
  

    </div>
    <div style=" position: fixed; left: 0; bottom: 0; padding-top:10px;width: 100%; background-color: #000000; color: white; text-align: center">
        <footer class="bg-light text-center text-lg-start">
            <p>&copy; @DateTime.Now.Year - Lavacar</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/myBundle")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/Login/Cerrar_Sesion.js"></script>
</body>
</html>